### ISSUE TITLE
Switch-to-buffer causes NPE in 2019.1

### ISSUE THREAD

**Issue by halcyon** [cursive-ide/emacs-plus#11]
Switch-to-buffer using `C-x b` results in NPE:

```
java.lang.NullPointerException
	at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.removeFromActions(SwitchToBuffer.java:153)
	at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.keySetup(SwitchToBuffer.java:67)
	at com.mulgasoft.emacsplus.actions.wrapper.SwitchToBuffer.actionPerformed(SwitchToBuffer.java:45)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:616)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:665)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:664)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inSecondStrokeInProgressState(IdeKeyEventDispatcher.java:389)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inWaitForSecondStrokeState(IdeKeyEventDispatcher.java:301)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:223)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:665)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Grannath** [comment]
Second this. But seems to work fine anyway. At least I did not notice anything so far.

**Comment by matt9j** [comment]
I have also run into this, it appears to break search in the switcher per issue #10 .
