### ISSUE TITLE
Some keybindings are gone in 2019.2

### ISSUE THREAD

**Issue by chkhd** [cursive-ide/emacs-plus#14]
`C-r`, `M-C-r` are gone for example, not quite sure why.

**Comment by chkhd** [comment]
Here is a log from IDE startup

```
Com.intellij.diagnostic.pluginexception: while loading class com.mulgasoft.emacsplus.actions.search.isearchbackward: class com.mulgasoft.emacsplus.actions.search.isearchbackward overrides final method com.intellij.openapi.editor.actionsystem.editoraction.actionperformed(lcom/intellij/openapi/actionsystem/anactionevent;)v [plugin: com.cursive-ide.emacsplus] [plugin: com.cursive-ide.emacsplus]
	at com.intellij.openapi.actionsystem.impl.actionmanagerimpl.instantiate(actionmanagerimpl.java:163)
	at com.intellij.openapi.actionsystem.impl.actionmanagerimpl.convertstub(actionmanagerimpl.java:139)
	at com.intellij.openapi.actionsystem.impl.actionmanagerimpl.getactionimpl(actionmanagerimpl.java:501)
	at com.intellij.openapi.actionsystem.impl.actionmanagerimpl.getaction(actionmanagerimpl.java:489)
	at com.intellij.openapi.actionsystem.impl.actionmanagerimpl.preloadactions(actionmanagerimpl.java:1327)
	at com.intellij.openapi.actionsystem.impl.actionpreloader.preload(actionpreloader.java:18)
	at com.intellij.openapi.application.preloader.lambda$null$1(preloader.java:74)
	at com.intellij.openapi.progress.impl.coreprogressmanager.lambda$runprocess$2(coreprogressmanager.java:169)
	at com.intellij.openapi.progress.impl.coreprogressmanager.registerindicatorandrun(coreprogressmanager.java:591)
	at com.intellij.openapi.progress.impl.coreprogressmanager.executeprocessunderprogress(coreprogressmanager.java:537)
	at com.intellij.openapi.progress.impl.progressmanagerimpl.executeprocessunderprogress(progressmanagerimpl.java:59)
	at com.intellij.openapi.progress.impl.coreprogressmanager.runprocess(coreprogressmanager.java:156)
	at com.intellij.openapi.application.preloader.lambda$componentsinitialized$2(preloader.java:71)
	at com.intellij.util.concurrency.boundedtaskexecutor.dorun(boundedtaskexecutor.java:207)
	at com.intellij.util.concurrency.boundedtaskexecutor.access$100(boundedtaskexecutor.java:29)
	at com.intellij.util.concurrency.boundedtaskexecutor$1.lambda$run$0(boundedtaskexecutor.java:185)
	at com.intellij.util.concurrencyutil.rununderthreadname(concurrencyutil.java:208)
	at com.intellij.util.concurrency.boundedtaskexecutor$1.run(boundedtaskexecutor.java:181)
	at java.base/java.util.concurrent.threadpoolexecutor.runworker(threadpoolexecutor.java:1128)
	at java.base/java.util.concurrent.threadpoolexecutor$worker.run(threadpoolexecutor.java:628)
	at java.base/java.lang.thread.run(thread.java:834)
caused by: com.intellij.diagnostic.pluginexception: while loading class com.mulgasoft.emacsplus.actions.search.isearchbackward: class com.mulgasoft.emacsplus.actions.search.isearchbackward overrides final method com.intellij.openapi.editor.actionsystem.editoraction.actionperformed(lcom/intellij/openapi/actionsystem/anactionevent;)v [plugin: com.cursive-ide.emacsplus]
	at com.intellij.ide.plugins.cl.pluginclassloader.loadclassinsideself(pluginclassloader.java:220)
	at com.intellij.ide.plugins.cl.pluginclassloader.tryloadingclass(pluginclassloader.java:165)
	at com.intellij.ide.plugins.cl.pluginclassloader.loadclass(pluginclassloader.java:73)
	at java.base/java.lang.classloader.loadclass(classloader.java:521)
	at java.base/java.lang.classloader.defineclass1(native method)
	at java.base/java.lang.classloader.defineclass(classloader.java:1016)
	at java.base/java.lang.classloader.defineclass(classloader.java:877)
	at com.intellij.util.lang.urlclassloader._defineclass(urlclassloader.java:335)
	at com.intellij.util.lang.urlclassloader.defineclass(urlclassloader.java:330)
	at com.intellij.util.lang.urlclassloader._findclass(urlclassloader.java:294)
	at com.intellij.ide.plugins.cl.pluginclassloader.loadclassinsideself(pluginclassloader.java:217)
	at com.intellij.ide.plugins.cl.pluginclassloader.tryloadingclass(pluginclassloader.java:165)
	at com.intellij.ide.plugins.cl.pluginclassloader.loadclass(pluginclassloader.java:73)
	at java.base/java.lang.classloader.loadclass(classloader.java:521)
	at java.base/java.lang.class.forname0(native method)
	at java.base/java.lang.class.forname(class.java:398)
	at com.intellij.openapi.actionsystem.impl.actionmanagerimpl.instantiate(actionmanagerimpl.java:151)
	... 20 more
caused by: java.lang.verifyerror: class com.mulgasoft.emacsplus.actions.search.isearchbackward overrides final method com.intellij.openapi.editor.actionsystem.editoraction.actionperformed(lcom/intellij/openapi/actionsystem/anactionevent;)v
	at java.base/java.lang.classloader.defineclass1(native method)
	at java.base/java.lang.classloader.defineclass(classloader.java:1016)
	at java.base/java.lang.classloader.defineclass(classloader.java:877)
	at com.intellij.util.lang.urlclassloader._defineclass(urlclassloader.java:335)
	at com.intellij.util.lang.urlclassloader.defineclass(urlclassloader.java:330)
	at com.intellij.util.lang.urlclassloader._findclass(urlclassloader.java:294)
	at com.intellij.ide.plugins.cl.pluginclassloader.loadclassinsideself(pluginclassloader.java:217)
	... 36 more
```

**Comment by mtyukala** [comment]
Go to Settings | Keymap to set keybindings back to Emacs+

**Comment by chkhd** [comment]
> Go to Settings | Keymap to set keybindings back to Emacs+

This will not fix the error, and will also reset personalised bindings.
